backend:
  name: github
  repo: realfaq/hugo-ivaness
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Посты"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Рубрики", name: "categories", widget: "list", required: false}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Описание", name: "description", widget: "text", required: false}
      - {label: "Главная картинка", name: "featuredImage", widget: "image", required: false}
      - {label: "Черновик", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Текст", name: "body", widget: "markdown"}
  
  - name: "pages"
    label: "Страницы"
    folder: "content"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    filter: {field: "type", value: "page"}
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Тип", name: "type", widget: "hidden", default: "page"}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Текст", name: "body", widget: "markdown"}
